matrix:
  include:
    - os: osx
      compiler: clang
      env:
        N=OSX
        LAST_CMD="./tests/resources/check_correctness.sh  -r -s -n && ./tests/resources/check_correctness.sh -r -s -e tests/resources/emf-corrupted/ -xNn"
    - os: linux
      dist: trusty
      compiler: clang
      env:
          N=BASE
          LAST_CMD="./tests/resources/check_correctness.sh  -r -s && ./tests/resources/check_correctness.sh -r -s -e tests/resources/emf-corrupted/ -xN"
    - os: linux
      dist: trusty
      env:
          N=GCOV
          CMAKE_ARG="-DGCOV=ON"
          LAST_CMD="make coverage"


sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcode-select --install;true; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install argp-standalone; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install valgrind; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libxml2; fi
  - if [[ "$N" == "GCOV" ]]; then pip install --user cpp-coveralls; fi

addons:
  apt:
    packages:
    - cmake
    - time
    - valgrind
    - libxml2-utils
    - libc6-dev
    - gcc
    - g++
    - gcc
    - g++
    - lcov


language: cpp


script: cmake . -DFORCELE=ON $CMAKE_ARG && make && $LAST_CMD 

after_success:
  - if [[ "$N" == "GCOV" ]];then ~/.local/bin/coveralls -E '*.CMakeFiles.*' -E '.*conv.*' -E '.*uemf.*' -E '.*upmf.*' -E '.*goodies.*' -E '.*tests.*' --gcov-options '\-lp';fi
