sudo: false

addons:
  apt:
    packages:
    - cmake
    - time
    - valgrind
    - libxml2-utils
    - libpolyclipping-dev
    - libc6-dev
    - gcc
    - g++

language: cpp

compiler: clang

script: cmake . && make && ./tests/resources/check_correctness.sh && ./tests/resources/check_correctness.sh -s -e tests/resources/emf-corrupted/ -xN
