version: 1.0.{build}

os: Visual Studio 2015

platform:
  - x64

configuration:
  - Release

build:
  project: C:/projects/libemf2svg/build/app.sln

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ..

test_script:
  - cmd: pwd
  - cmd: ls
